#pragma once

#include <queue>

inline std::queue<int> *global_msg_queue;

enum ThermostatMessages
{
	SAMPLE_AIR,
	RTC_UPDATE,
	GET_EPOCH,
	UPDATE_SAMPLE_PERIOD,
	UPDATE_SAMPLE_SUM,
	MOTION_DETECTED,
	NO_MOTION,
	START_SCREEN_TIMEOUT,
	CHECK_FOR_UDP_MSG,
	UPDATE_SCHEDULE,
	START_TEMPORARY_OVERRIDE,
	GET_TEMPORARY_OVERRIDE,
	SEND_SERVER_TEMPERATURE,
	SEND_SERVER_STATS,
	SEND_SERVER_MOTION,
	SEND_SEVER_RUNTIME, // 15
	SEND_SERVER_FURNACE_STATE,
	OLED_ON,
	OLED_OFF,
	OLED_UPDATE,
	OLED_NEXT_MENU, // 20
	OLED_PREV_MENU,
	OLED_EDIT_MENU,
	OLED_ROTARY_CCW,
	OLED_ROTARY_CW
};
